org.gradle.jvmargs=-Xmx4096M
org.gradle.daemon = false
#loom.ignoreDependencyLoomVersionValidation = true
#loom.allowMismatchedPlatformVersions = true
#fabric.loom.multiProjectOptimisation = false

# Mc stuff
minecraft_version = 1.21.5
minecraft_min_version = 1.21.5
minecraft_max_version = 1.22

enabled_platforms = fabric,neoforge
pack_format_number = 20

# Mod stuff
mod_id = modelfix
mod_name = Model Gap Fix
mod_version = 1.21.5-1.12
mod_license = GLP3
mod_group_id = net.mehvahdjukaar
mod_authors = MehVahdJukaar
mod_description = Removes small gaps in item and block models
mod_homepage = https://www.curseforge.com/minecraft/mc-mods/model-gap-fix
mod_github = https://github.com/MehVahdJukaar/modelfix-multi
mod_credits = MehVahdJukaar

project_id = 676136


# Loaders

parchment_version = 1.21:2024.07.28
quilt_version = 1.21+build.2:v2

fabric_loader_version = 0.16.10
fabric_api_version = 0.119.5+1.21.5


neo_version = 21.5.4-beta
neo_version_range = *
loader_version_range = *

modmenu_version = 14.0.0-rc.2
yacl_version = 3.6.6+1.21.5-fabric
cloth_version = 15.0.127








