org.gradle.jvmargs=-Xmx4096M
org.gradle.daemon = false
#loom.ignoreDependencyLoomVersionValidation = true
#loom.allowMismatchedPlatformVersions = true
#fabric.loom.multiProjectOptimisation = false

# Mc stuff
minecraft_version = 1.21.3
minecraft_min_version = 1.21.2
minecraft_max_version = 1.22

enabled_platforms = fabric,neoforge
pack_format_number = 20

# Mod stuff
mod_id = modelfix
mod_name = Model Gap Fix
mod_version = 1.21.3-1.12
mod_license = GLP3
mod_group_id = net.mehvahdjukaar
mod_authors = MehVahdJukaar
mod_description = Removes small gaps in item and block models
mod_homepage = https://www.curseforge.com/minecraft/mc-mods/model-gap-fix
mod_github = https://github.com/MehVahdJukaar/model-gap-fix
mod_credits = MehVahdJukaar

project_id = 676136


# Loaders

parchment_version = 1.21:2024.07.28
quilt_version = 1.21+build.2:v2

fabric_loader_version = 0.16.9
fabric_api_version = 0.107.0+1.21.3


neo_version = 21.3.3-beta
neo_version_range = *
loader_version_range = *

modmenu_version = 11.0.0
cloth_version = 15.0.127








